import Head from 'next/head'
import styles from '../styles/Home.module.css'
import SideComponent from './sidecomponent/SideComponent';
import SmoothList from 'react-smooth-list';
import Image from 'next/image'
const webdevImaage = require('../public/webdev.png');
const profImage = require('../public/userImage.png');

import { FiMenu } from 'react-icons/fi';
import { IoIosArrowDown } from 'react-icons/io';
import { FaLinkedinIn, FaInstagram, FaFacebookF, FaTwitter, FaUserCircle, FaUser } from 'react-icons/fa';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Joao da Costa | Resume</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Nunito+Sans&display=swap" rel="stylesheet"/>
      </Head>

      <div className={styles.interface}>
        <div className={styles.sidecomp_box}>
          <SideComponent/>
        </div>
        <div>
          <div className={styles.topSide}>
            <div className={styles.mobile_menu_box}>
              <FiMenu className={styles.menuIcon}/>
            </div>

            <div className={styles.topSide_left}>
              <div className={styles.profile_image_and_name_box}>
                <div>
                  <h4 className={styles.userName}>JOAO DA COSTA</h4>
                  <p className={styles.office}>Software developer</p>
                </div>
                
                <div className={styles.profileBox}>
                  <div className={styles.profileImageBox}>
                    <Image src={profImage} alt="profile"/>
                  </div>
                  <div className={styles.online_dot}/>
                </div>
              </div>
              
              <p className={styles.details}>Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado.</p>
              <div className={styles.btns_box}>
                <button className={styles.portfolio_btn}>Portfolio</button>
                <button className={styles.resume_btn}>Download Resume</button>
              </div>

              <div className={styles.icons}>
                <div className={styles.icon_box}><FaLinkedinIn/></div>
                <div className={styles.icon_box}><FaInstagram/></div>
                <div className={styles.icon_box}><FaTwitter/></div>
                <div className={styles.icon_box}><FaFacebookF/></div>
              </div>
            </div>

            <div className={styles.topSide_right}>
              <Image className={styles.webdevIma} width={300} height={280} src={webdevImaage} alt="webdev"/>
            </div>
          </div>

          <div className={styles.bottomSide}>

            <SmoothList visible={true}>
              <div>
                <h5 className={styles.details_mobile}>Details</h5>
                <IoIosArrowDown className={styles.arrowDown}/>
                <p className={styles.details_text}>Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente inalterado.</p>
              </div>
              
              <div>
                <h5 className={styles.what_I_do}>What i do</h5>
                <IoIosArrowDown className={styles.arrowDown}/>
                <p className={styles.what_I_do_details}>Lorem Ipsum sobreviveu não só a cinco séculos, como também ao salto para a editoração eletrônica, permanecendo essencialmente <span className={styles.what_I_do_details_last_word}>inalterado.</span></p>
              </div>
              
              <div className={styles.technologies}>
                <p>React</p>
                <p>Javascript</p>
                <p>Html</p>
                <p>Css</p>
                <p>React-Native</p>
                <p>Node</p>
                <p>Mysql</p>
              </div>
            </SmoothList>
            
            <form className={styles.form_box}>
              <input type="email" placeholder="Email" required/>
              <input type="text" placeholder="Company name" required/>
              <textarea placeholder="Tell me more about your interest"></textarea>
            </form>

          </div>
        </div>
        
      </div>
    </div>
  )
}
